package com.example.valparaisoapp.ui.slideshow;

public class FormatNewSGMF {
    public boolean activo;
    public String tiporoca;
    public String gradometeor;
    public String gradofractura;
    public String tiposuelo;
    public String tamanograno;
    public String tiporelieve;
    public String indicerelieve;
    public String inclinacionladera;
    public String longiladera;
    public String formaladera;
    public String formacresta;
    public String formavalle;
    public String cobertura;
    public String uso;
    public String densidad;
    public String frecuencia;
    public String textura;
    public String patron;
    public String tipoerosion;
    public String espaciamiento;
    public String intensidaderosion;
//    public String tipodemm;
//    public String tipomaterial;
    public String actividad;
    public String codigonuevaSGMF;
    public String coberturaotro;
    public String usootro;
    public String patronotro;

    public String tipodemm0check;
    public String tipodemm1check;
    public String tipodemm2check;
    public String tipodemm3check;
    public String tipodemm4check;
    public String tipodemm5check;
    public String tipodemm6check;
    public String tipodemm7check;
    public String tipodemm8check;

    public String tipomaterial0check;
    public String tipomaterial1check;
    public String tipomaterial2check;
    public String tipomaterial3check;
    public String tipomaterial4check;

    public FormatNewSGMF(boolean activo, String tiporoca, String gradometeor, String gradofractura, String tiposuelo, String tamanograno, String tiporelieve, String indicerelieve, String inclinacionladera, String longiladera, String formaladera, String formacresta, String formavalle, String cobertura, String uso, String densidad, String frecuencia, String textura, String patron, String tipoerosion, String espaciamiento, String intensidaderosion, String actividad, String codigonuevaSGMF, String coberturaotro, String usootro, String patronotro, String tipodemm0check, String tipodemm1check, String tipodemm2check, String tipodemm3check, String tipodemm4check, String tipodemm5check, String tipodemm6check, String tipodemm7check, String tipodemm8check, String tipomaterial0check, String tipomaterial1check, String tipomaterial2check, String tipomaterial3check, String tipomaterial4check) {
        this.activo = activo;
        this.tiporoca = tiporoca;
        this.gradometeor = gradometeor;
        this.gradofractura = gradofractura;
        this.tiposuelo = tiposuelo;
        this.tamanograno = tamanograno;
        this.tiporelieve = tiporelieve;
        this.indicerelieve = indicerelieve;
        this.inclinacionladera = inclinacionladera;
        this.longiladera = longiladera;
        this.formaladera = formaladera;
        this.formacresta = formacresta;
        this.formavalle = formavalle;
        this.cobertura = cobertura;
        this.uso = uso;
        this.densidad = densidad;
        this.frecuencia = frecuencia;
        this.textura = textura;
        this.patron = patron;
        this.tipoerosion = tipoerosion;
        this.espaciamiento = espaciamiento;
        this.intensidaderosion = intensidaderosion;
        this.actividad = actividad;
        this.codigonuevaSGMF = codigonuevaSGMF;
        this.coberturaotro = coberturaotro;
        this.usootro = usootro;
        this.patronotro = patronotro;
        this.tipodemm0check = tipodemm0check;
        this.tipodemm1check = tipodemm1check;
        this.tipodemm2check = tipodemm2check;
        this.tipodemm3check = tipodemm3check;
        this.tipodemm4check = tipodemm4check;
        this.tipodemm5check = tipodemm5check;
        this.tipodemm6check = tipodemm6check;
        this.tipodemm7check = tipodemm7check;
        this.tipodemm8check = tipodemm8check;
        this.tipomaterial0check = tipomaterial0check;
        this.tipomaterial1check = tipomaterial1check;
        this.tipomaterial2check = tipomaterial2check;
        this.tipomaterial3check = tipomaterial3check;
        this.tipomaterial4check = tipomaterial4check;
    }
}
