package com.example.valparaisoapp.ui.slideshow;

public class FormatUGSSuelos {
    public boolean activo;
    public String municipios;
    public String claseaflor;
    public String estructurasoporte1;
    public String estructurasoporte2;
    public String condicionhumedad1;
    public String condicionhumedad2;
    public String estructurasrelictas1;
    public String estructurasrelictas2;
//    public String granulometria1;
//    public String granulometria2;
//    public String forma1;
//    public String forma2;
//    public String redondez1;
//    public String redondez2;
    public String orientacion1;
    public String orientacion2;
    public String dirimbricacion1;
    public String dirimbricacion2;
    public String meteorizacionclastos1;
    public String meteorizacionclastos2;
//    public String granulometriamatriz1;
//    public String granulometriamatriz2;
    public String gradacion1;
    public String gradacion2;
    public String seleccion1;
    public String seleccion2;
    public String plasticidad1;
    public String plasticidad2;
    public String resiscorte1;
    public String resiscorte2;
//    public String formasuelosgruesos1;
//    public String formasuelosgruesos2;
//    public String redondezsuelosgruesos1;
//    public String redondezsuelosgruesos2;
//    public String orientacionsuelosgruesos1;
//    public String orientacionsuelosgruesos2;
    public String compacidadsuelosgruesos1;
    public String compacidadsuelosgruesos2;
//    public String dirimbricacionmatriz1;
//    public String dirimbricacionmatriz2;
    public String noformato;
    public String vereda;
    public String noestacion;
    public String secuenciaestratiopt1orden;
    public String secuenciaestratiopt1espesor;
    public String secuenciaestratiopt2orden;
    public String secuenciaestratiopt2espesor;
    public String secuenciaestratiopt3orden;
    public String secuenciaestratiopt3espesor;
    public String secuenciaestratisuelor1orden;
    public String secuenciaestratisuelor1espesor;
    public String secuenciaestratisuelor2orden;
    public String secuenciaestratisuelor2espesor;
    public String secuenciaestratisuelor3orden;
    public String secuenciaestratisuelor3espesor;
    public String litologiasasociadasopt1exist;
    public String litologiasasociadasopt1espesor;
    public String litologiasasociadasopt2exist;
    public String litologiasasociadasopt2espesor;
    public String nombreugs;
    public String porcentajematriz1;
    public String porcentajematriz2;
    public String porcentajeclastos1;
    public String porcentajeclastos2;
    public String color1;
    public String color2;
    public String observacionessuelos;
    public String descripcionsuelos;

    public String forma0check_2;
    public String forma1check_2;
    public String forma2check_2;
    public String forma3check_2;
    public String forma4check_2;

    public String forma0check_1;
    public String forma1check_1;
    public String forma2check_1;
    public String forma3check_1;
    public String forma4check_1;

    public String redondez0check_2;
    public String redondez1check_2;
    public String redondez2check_2;
    public String redondez3check_2;
    public String redondez4check_2;
    public String redondez5check_2;

    public String redondez0check_1;
    public String redondez1check_1;
    public String redondez2check_1;
    public String redondez3check_1;
    public String redondez4check_1;
    public String redondez5check_1;


    public String granulometria0_2;
    public String granulometria1_2;
    public String granulometria2_2;
    public String granulometria3_2;
    public String granulometria4_2;
    public String granulometria5_2;

    public String granulometria0_1;
    public String granulometria1_1;
    public String granulometria2_1;
    public String granulometria3_1;
    public String granulometria4_1;
    public String granulometria5_1;

    public String granulometriamatriz0_2;
    public String granulometriamatriz1_2;
    public String granulometriamatriz2_2;
    public String granulometriamatriz3_2;
    public String granulometriamatriz4_2;
    public String granulometriamatriz5_2;
    public String granulometriamatriz6_2;
    public String granulometriamatriz7_2;

    public String granulometriamatriz0_1;
    public String granulometriamatriz1_1;
    public String granulometriamatriz2_1;
    public String granulometriamatriz3_1;
    public String granulometriamatriz4_1;
    public String granulometriamatriz5_1;
    public String granulometriamatriz6_1;
    public String granulometriamatriz7_1;

    public FormatUGSSuelos(boolean activo, String municipios, String claseaflor, String estructurasoporte1, String estructurasoporte2, String condicionhumedad1, String condicionhumedad2, String estructurasrelictas1, String estructurasrelictas2, String orientacion1, String orientacion2, String dirimbricacion1, String dirimbricacion2, String meteorizacionclastos1, String meteorizacionclastos2, String gradacion1, String gradacion2, String seleccion1, String seleccion2, String plasticidad1, String plasticidad2, String resiscorte1, String resiscorte2, String compacidadsuelosgruesos1, String compacidadsuelosgruesos2, String noformato, String vereda, String noestacion, String secuenciaestratiopt1orden, String secuenciaestratiopt1espesor, String secuenciaestratiopt2orden, String secuenciaestratiopt2espesor, String secuenciaestratiopt3orden, String secuenciaestratiopt3espesor, String secuenciaestratisuelor1orden, String secuenciaestratisuelor1espesor, String secuenciaestratisuelor2orden, String secuenciaestratisuelor2espesor, String secuenciaestratisuelor3orden, String secuenciaestratisuelor3espesor, String litologiasasociadasopt1exist, String litologiasasociadasopt1espesor, String litologiasasociadasopt2exist, String litologiasasociadasopt2espesor, String nombreugs, String porcentajematriz1, String porcentajematriz2, String porcentajeclastos1, String porcentajeclastos2, String color1, String color2, String observacionessuelos, String descripcionsuelos, String forma0check_2, String forma1check_2, String forma2check_2, String forma3check_2, String forma4check_2, String forma0check_1, String forma1check_1, String forma2check_1, String forma3check_1, String forma4check_1, String redondez0check_2, String redondez1check_2, String redondez2check_2, String redondez3check_2, String redondez4check_2, String redondez5check_2, String redondez0check_1, String redondez1check_1, String redondez2check_1, String redondez3check_1, String redondez4check_1, String redondez5check_1, String granulometria0_2, String granulometria1_2, String granulometria2_2, String granulometria3_2, String granulometria4_2, String granulometria5_2, String granulometria0_1, String granulometria1_1, String granulometria2_1, String granulometria3_1, String granulometria4_1, String granulometria5_1, String granulometriamatriz0_2, String granulometriamatriz1_2, String granulometriamatriz2_2, String granulometriamatriz3_2, String granulometriamatriz4_2, String granulometriamatriz5_2, String granulometriamatriz0_1, String granulometriamatriz1_1, String granulometriamatriz2_1, String granulometriamatriz3_1, String granulometriamatriz4_1, String granulometriamatriz5_1, String granulometriamatriz6_1, String granulometriamatriz7_1, String granulometriamatriz6_2, String granulometriamatriz7_2) {
        this.activo = activo;
        this.municipios = municipios;
        this.claseaflor = claseaflor;
        this.estructurasoporte1 = estructurasoporte1;
        this.estructurasoporte2 = estructurasoporte2;
        this.condicionhumedad1 = condicionhumedad1;
        this.condicionhumedad2 = condicionhumedad2;
        this.estructurasrelictas1 = estructurasrelictas1;
        this.estructurasrelictas2 = estructurasrelictas2;
        this.orientacion1 = orientacion1;
        this.orientacion2 = orientacion2;
        this.dirimbricacion1 = dirimbricacion1;
        this.dirimbricacion2 = dirimbricacion2;
        this.meteorizacionclastos1 = meteorizacionclastos1;
        this.meteorizacionclastos2 = meteorizacionclastos2;
        this.gradacion1 = gradacion1;
        this.gradacion2 = gradacion2;
        this.seleccion1 = seleccion1;
        this.seleccion2 = seleccion2;
        this.plasticidad1 = plasticidad1;
        this.plasticidad2 = plasticidad2;
        this.resiscorte1 = resiscorte1;
        this.resiscorte2 = resiscorte2;

        this.compacidadsuelosgruesos1 = compacidadsuelosgruesos1;
        this.compacidadsuelosgruesos2 = compacidadsuelosgruesos2;

        this.noformato = noformato;
        this.vereda = vereda;
        this.noestacion = noestacion;
        this.secuenciaestratiopt1orden = secuenciaestratiopt1orden;
        this.secuenciaestratiopt1espesor = secuenciaestratiopt1espesor;
        this.secuenciaestratiopt2orden = secuenciaestratiopt2orden;
        this.secuenciaestratiopt2espesor = secuenciaestratiopt2espesor;
        this.secuenciaestratiopt3orden = secuenciaestratiopt3orden;
        this.secuenciaestratiopt3espesor = secuenciaestratiopt3espesor;
        this.secuenciaestratisuelor1orden = secuenciaestratisuelor1orden;
        this.secuenciaestratisuelor1espesor = secuenciaestratisuelor1espesor;
        this.secuenciaestratisuelor2orden = secuenciaestratisuelor2orden;
        this.secuenciaestratisuelor2espesor = secuenciaestratisuelor2espesor;
        this.secuenciaestratisuelor3orden = secuenciaestratisuelor3orden;
        this.secuenciaestratisuelor3espesor = secuenciaestratisuelor3espesor;
        this.litologiasasociadasopt1exist = litologiasasociadasopt1exist;
        this.litologiasasociadasopt1espesor = litologiasasociadasopt1espesor;
        this.litologiasasociadasopt2exist = litologiasasociadasopt2exist;
        this.litologiasasociadasopt2espesor = litologiasasociadasopt2espesor;
        this.nombreugs = nombreugs;
        this.porcentajematriz1 = porcentajematriz1;
        this.porcentajematriz2 = porcentajematriz2;
        this.porcentajeclastos1 = porcentajeclastos1;
        this.porcentajeclastos2 = porcentajeclastos2;
        this.color1 = color1;
        this.color2 = color2;
        this.observacionessuelos = observacionessuelos;
        this.descripcionsuelos = descripcionsuelos;
        this.forma0check_2 = forma0check_2;
        this.forma1check_2 = forma1check_2;
        this.forma2check_2 = forma2check_2;
        this.forma3check_2 = forma3check_2;
        this.forma4check_2 = forma4check_2;
        this.forma0check_1 = forma0check_1;
        this.forma1check_1 = forma1check_1;
        this.forma2check_1 = forma2check_1;
        this.forma3check_1 = forma3check_1;
        this.forma4check_1 = forma4check_1;
        this.redondez0check_2 = redondez0check_2;
        this.redondez1check_2 = redondez1check_2;
        this.redondez2check_2 = redondez2check_2;
        this.redondez3check_2 = redondez3check_2;
        this.redondez4check_2 = redondez4check_2;
        this.redondez5check_2 = redondez5check_2;
        this.redondez0check_1 = redondez0check_1;
        this.redondez1check_1 = redondez1check_1;
        this.redondez2check_1 = redondez2check_1;
        this.redondez3check_1 = redondez3check_1;
        this.redondez4check_1 = redondez4check_1;
        this.redondez5check_1 = redondez5check_1;
        this.granulometria0_2 = granulometria0_2;
        this.granulometria1_2 = granulometria1_2;
        this.granulometria2_2 = granulometria2_2;
        this.granulometria3_2 = granulometria3_2;
        this.granulometria4_2 = granulometria4_2;
        this.granulometria5_2 = granulometria5_2;
        this.granulometria0_1 = granulometria0_1;
        this.granulometria1_1 = granulometria1_1;
        this.granulometria2_1 = granulometria2_1;
        this.granulometria3_1 = granulometria3_1;
        this.granulometria4_1 = granulometria4_1;
        this.granulometria5_1 = granulometria5_1;
        this.granulometriamatriz0_2 = granulometriamatriz0_2;
        this.granulometriamatriz1_2 = granulometriamatriz1_2;
        this.granulometriamatriz2_2 = granulometriamatriz2_2;
        this.granulometriamatriz3_2 = granulometriamatriz3_2;
        this.granulometriamatriz4_2 = granulometriamatriz4_2;
        this.granulometriamatriz5_2 = granulometriamatriz5_2;
        this.granulometriamatriz6_2 = granulometriamatriz5_2;
        this.granulometriamatriz7_2 = granulometriamatriz5_2;
        this.granulometriamatriz0_1 = granulometriamatriz0_1;
        this.granulometriamatriz1_1 = granulometriamatriz1_1;
        this.granulometriamatriz2_1 = granulometriamatriz2_1;
        this.granulometriamatriz3_1 = granulometriamatriz3_1;
        this.granulometriamatriz4_1 = granulometriamatriz4_1;
        this.granulometriamatriz5_1 = granulometriamatriz5_1;
        this.granulometriamatriz6_1 = granulometriamatriz5_1;
        this.granulometriamatriz7_1 = granulometriamatriz5_1;
    }
}
